[package]
name = "solana-memory-management"
version = "1.15.0"
description = "Solana memory management"
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
repository = "https://github.com/kindtek/solana"
homepage = "https://solana.com/"
license = "Apache-2.0"
edition = "2021"
